name: community-release-notifier
on:
  release:
    types: [prereleased]

jobs:
  discord-release:
    # if: github.repository_owner == 'Acode-Foundation'
    runs-on: ubuntu-latest
    steps:
    - name: Get Release Content
      id: get-release-content
      uses: 2428392/gh-truncate-string-action@b3ff790d21cf42af3ca7579146eedb93c8fb0757 # v1.4.1
      with:
        maxLength: 2000
        stringToTruncate: |
          ðŸ“¢ Acode [${{ github.event.release.tag_name }}](<${{ github.event.release.url }}>) was just Released ðŸŽ‰!
          

    - name: Discord Webhook Action (Publishing)
      uses: tsickert/discord-webhook@c840d45a03a323fbc3f7507ac7769dbd91bfb164 # v5.3.0
      with:
        webhook-url: ${{ secrets.DISCORD_WEBHOOK_RELEASE_NOTES }}
        content: ${{ steps.get-release-content.outputs.string }}