name: On Demand Preview Releases for PR
#  avoids paths like .md, and anything in .github folder
on:
  pull_request:
    paths-ignore:
      - '!*.md'
#      - '.github/**'
    types: [labeled, synchronize]


permissions:
  contents: write
  pull-requests: write
  # All Pull Requests are issues, but not all issues are Pull Requests (like GitHub says ðŸ™ƒ)
  issues: write

concurrency:
  # Allow only one workflow per any non-`main` branch.
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.ref_name == 'main' && github.sha || 'anysha' }}
  cancel-in-progress: true

jobs:
  job_trigger:
    name: Trigger Preview Release (if conditions met)
    if: |
      (!contains(github.event.pull_request.labels.*.name, 'DO NOT PREVIEW RELEASE') 
      && (contains(github.event.pull_request.labels.*.name, 'Bypass check - PREVIEW RELEASE') 
      || contains(github.event.pull_request.labels.*.name, 'CI: RUN ON-DEMAND PREVIEW RELEASES')))

    runs-on: ubuntu-latest
    # if: github.repository_owner == 'Acode-Foundation'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          clean: false
          fetch-depth: 0

      - name: Remove Manually added PR Label
        if: |
          contains(github.event.pull_request.labels.*.name, 'CI: RUN ON-DEMAND PREVIEW RELEASES')

        run: gh pr edit $PR --remove-label "$labels"
        env:
           PR: ${{ github.event.pull_request.number }}
           labels: 'CI: RUN ON-DEMAND PREVIEW RELEASES'
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Add comment to PR
        run: |
            git config --global user.name 'GitHub Actions'
            git config --global user.email 'github-actions@github.com'
            gh pr comment $PR --body "âš’ï¸ Starting a workflow to build, Your On-Demand Preview Release/build for ${{ github.event.pull_request.url }}. \n\n status: **\`ðŸŸ¡ in_progress\`** \n\n Kindly wait, this message will be updated with success or failure status."
        env:
          PR: ${{ github.event.pull_request.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger Nightly Release Builder Workflow
        id: nightly_release_builder
        continue-on-error: true
        uses: unschooledgamer/acode/.github/workflows/nightly-build.yml@d651aa4a72cde52e5f59fcd5f50a6f4a8766b9f2
        with:
          is_PR: true
          PR_NUMBER: ${{ github.event.pull_request.number }}


      - name: Update Last Comment by bot (if Workflow Triggering failed)
#        ".outcome" -> result of a completed step before continue-on-error is applied
        if: steps.nightly_release_builder.outcome == 'failure'
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions@github.com'
          gh pr comment --edit-last $PR --body "ðŸ”´ (Workflow Trigger failure), Your On-Demand Preview Release/build for ${{ github.event.pull_request.url}}. \n\n status: **\`ðŸ”´ failed\`** \n For Owners: Please check the workflow at https://${{ github.server_url }}/${{ github.repository}}/actions"
        env:
          PR: ${{ github.event.pull_request.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}